server {
  listen 80;
  server_name 10.232.100.68;

  root /usr/share/nginx/html;
  index index.html;

  # Giữ nguyên port phía client (:3001)
  absolute_redirect off;

  # React SPA: cho phép chạy /login, /index và các route khác
  location / {
    try_files $uri $uri/ /index.html;
  }
}